name: Ubuntu

on:
  - push
  - pull_request

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: .local

jobs:
  build:  
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v4
      
    - name: cache dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
        key: ${{ runner.os }}-dependencies

    - name: install make
      run: |
        cd ..
        sudo apt-get install build-essential
        gcc -v
        make -v
    - name: install valgrind
      run: |
        sudo apt-get install valgrind
    - name: clean
      run: |
       rm -rf ./build/*
    - name: build
      run: |
        make BUILD
    - name: Run tests
      run: |
        make TEST
    - name: Leak test
      run: |
        make LEAK